### ISSUE TITLE
Login 

### ISSUE THREAD

**Issue by BloodDragon2580** [Dalufishe/palserver-online-map#1]
Hey my friend, a version without manuell login will be nice i think. Mark in the files what must be changed to auto login. For users there dont know how to do it. So users can include the map to theres Homepage for there players.

**Comment by Dalufishe** [comment]
Do you mean upload palworldsettings.ini ?

**Comment by BloodDragon2580** [comment]
No i mean connect to server with included login so we dont need to add IP Port and password. So we open the map at Browser and it Auto connect.

**Comment by Dalufishe** [comment]
I got it, you mean run locally and configuare settings in file? (like .env)

**Comment by BloodDragon2580** [comment]
Yes you got it

**Comment by BloodDragon2580** [comment]
Like here
https://github.com/fa0311/palworld-map

**Comment by BloodDragon2580** [comment]
I have tested now your map but no player is showing:
![Screenshot 2024-04-21 143211](https://github.com/Dalufishe/palserver-online-map/assets/1429236/783d5d42-d1c9-426c-8558-3a3c2c784a5d)

**Comment by Dalufishe** [comment]
do you run locally or website?

**Comment by BloodDragon2580** [comment]
website

**Comment by Dalufishe** [comment]
Ip: 127.0.0.1
Port: your rest api port (default: 8212)
Password: your admin password

**Comment by BloodDragon2580** [comment]
nope dont work
